package com.steleot.jetpackcompose.playground

object MainNavRoutes {
    const val Main = "main"
    const val Search = "search"
    const val Activity = "activity"
    const val Animation = "animation"
    const val ConstraintLayout = "constraint layout"
    const val CustomExamples = "custom examples"
    const val ExternalLibraries = "external libraries"
    const val Foundation = "foundation"
    const val FoundationLayout = "foundation layout"
    const val Material = "material"
    const val MaterialIcons = "material icons"
    const val MaterialIConsExtended = "material icons extended"
    const val Navigation = "navigation"
    const val Paging = "paging"
    const val Runtime = "runtime"
    const val Ui = "ui"
    const val ViewModel = "view model"
    const val Settings = "settings"
}

object ActivityNavRoutes {
    const val BackHandler = "back handler"
    const val LauncherForActivityResult = "launch for activity result"
}

object AnimationNavRoutes {
    const val Animatable = "animatable"
    const val AnimatedValues = "animated values"
    const val AnimatedVisibility = "animated visibility"
    const val AnimationModifier = "animation Modifier"
    const val CrossfadeAnimation = "crossfade animation"
    const val DoubleTapToLike = "double tap to like"
    const val GestureAnimation = "gesture animation"
    const val InfiniteTransition = "infinite transition"
    const val RotatingShape = "rotating shape"
    const val SingleValueColorAnimation = "single value color animation"
    const val SingleValueFloatAnimation = "single value float animation"
    const val SuspendAnimation = "suspend animation"
}

object ConstraintLayoutNavRoutes {
    const val Barrier = "barrier"
    const val Chain = "chain"
    const val ConstraintSet = "constraint set"
    const val CreateRefs = "create refs"
}

object FoundationNavRoutes {
    const val Background = "background"
    const val Border = "border"
    const val Canvas = "canvas"
    const val Clickable = "clickable"
    const val ClickableText = "clickable text"
    const val DragGestureDetector = "drag gesture detector"
    const val Draggable = "draggable"
    const val Focusable = "focusable"
    const val Image = "image"
    const val InteractionSource = "interaction source"
    const val LazyColumn = "lazy column"
    const val LazyGrid = "lazy grid"
    const val LazyRow = "lazy row"
    const val Scrollable = "scrollable"
    const val Scroller = "scroller"
    const val SelectionContainer = "selection container"
    const val Shape = "shape"
    const val StickyHeader = "sticky header"
    const val Toggeable = "toggeable"
    const val TransformGesture = "transform gesture"
    const val Transformable = "transformable"
}

object FoundationLayoutNavRoutes {
    const val AspectRatio = "aspect ratio"
    const val Box = "box"
    const val BoxWithConstraints = "box with constraints"
    const val Column = "column"
    const val Intrinsic = "intrinsic"
    const val Offset = "offset"
    const val Padding = "padding"
    const val Row = "row"
    const val Size = "size"
    const val Spacer = "spacer"
}

object MaterialNavRoutes {
    const val AlertDialog = "alert dialog"
    const val BackdropScaffold = "backdrop scaffold"
    const val BottomAppBar = "bottom app bar"
    const val BottomDrawer = "bottom drawer layout"
    const val BottomNavigation = "bottom navigation"
    const val BottomSheetScaffold = "bottom sheet scaffold"
    const val Button = "button"
    const val Card = "card"
    const val Checkbox = "checkbox"
    const val Divider = "divider"
    const val DropdownMenu = "dropdown menu"
    const val FloatingActionButton = "floating action button"
    const val ExtendedFloatingActionButton = "extended floating action button"
    const val Elevation = "elevation"
    const val IconButton = "icon button"
    const val IconToggleButton = "icon toggle button"
    const val Icon = "icon"
    const val ModalBottomSheetLayout = "modal bottom sheet layout"
    const val ModalDrawer = "modal drawer"
    const val ListItem = "list item"
    const val LocalContentAlpha = "local content alpha"
    const val LocalContentColor = "local content color"
    const val OutlinedTextField = "outlined text field"
    const val Progress = "progress"
    const val RadioButton = "radio button"
    const val Scaffold = "scaffold"
    const val ScrollableTabRow = "scrollable Tab row"
    const val Slider = "slider"
    const val SnackBar = "snackBar"
    const val Surface = "surface"
    const val Swipeable = "swipeable"
    const val SwipeToDismiss = "swipe to dismiss"
    const val Switch = "switch"
    const val TabRow = "tab row"
    const val TextField = "text field"
    const val Text = "text"
    const val TopAppBar = "top app bar"
    const val TriStateCheckbox = "tri state checkbox"
}

object MaterialIconsNavRoutes {
    const val Filled = "filled"
    const val Outlined = "outlined"
    const val Rounded = "rounded"
    const val Sharp = "sharp"
    const val TwoTone = "twotone"
}

object MaterialIconsExtendedNavRoutes {
    const val ExtendedFilled = "extended filled"
    const val ExtendedOutlined = "extended outlined"
    const val ExtendedRounded = "extended rounded"
    const val ExtendedSharp = "extended sharp"
    const val ExtendedTwoTone = "extended twotone"
}

object RuntimeNavRoutes {
    const val CollectAsState = "collect as state"
    const val CompositionLocal = "composition local"
    const val DerivedState = "derived state"
    const val DisposableEffect = "disposable effect"
    const val Immutable = "immutable"
    const val Key = "key"
    const val LaunchedEffect = "launched effect"
    const val MutableStateList = "mutableState list"
    const val MutableStateMap = "mutableState map"
    const val ProduceState = "produce state"
    const val RememberCoroutineScope = "remember coroutine scope"
    const val RememberSaveable = "remember saveable"
    const val RememberSaveableStateHolder = "remember saveable state holder"
    const val Remember = "remember"
    const val Saver = "saver"
    const val SideEffect = "side effect"
    const val SnapshotFlow = "snapshot flow"
}

object UiNavRoutes {
    const val AlignmentLine = "alignment line"
    const val Alpha = "alpha"
    const val AndroidViewBinding = "android view binding"
    const val AnimatedVector = "animated vector"
    const val AnnotatedString = "annotated string"
    const val Brush = "brush"
    const val Clip = "clip"
    const val Color = "color"
    const val DebugInspectorInfo = "debug inspector info"
    const val Dialog = "dialog"
    const val Drawable = "drawable"
    const val Font = "font"
    const val GraphicsLayer = "graphics layer"
    const val Layout = "layout"
    const val LocalAccessibilityManager = "local accessibility manager"
    const val LocalAutofill = "local autofill"
    const val LocalAutofillTree = "local autofill tree"
    const val LocalClipboardManager = "local clipboard manager"
    const val LocalConfiguration = "local configuration"
    const val LocalContext = "local context"
    const val LocalDensity = "local density"
    const val LocalFocusManager = "local focus manager"
    const val LocalFontLoader = "local font loader"
    const val LocalHapticFeedback = "local haptic feedback"
    const val LocalLayoutDirection = "local layout direction"
    const val LocalLifecycleOwner = "local lifecycle owner"
    const val LocalSavedStateRegistryOwner = "local saved state registry owner"
    const val LocalSoftwareKeyboardController = "local software keyboard controller"
    const val LocalTextInputService = "local text input service"
    const val LocalTextToolbar = "local text toolbar"
    const val LocalUriHandler = "local uri handler"
    const val LocalViewConfiguration = "local view configuration"
    const val LocalWindowInfo = "local window info"
    const val NestedScroll = "nested scroll"
    const val OnGloballyPositioned = "on globally positioned"
    const val OnSizeChanged = "on size changed"
    const val PathEffect = "path effect"
    const val Popup = "popup"
    const val Primitive = "primitive"
    const val Rotate = "rotate"
    const val Scale = "scale"
    const val Shadow = "shadow"
    const val SpanStyle = "span style"
    const val String = "string"
    const val SubComposeLayout = "sub compose layout"
    const val TextDecoration = "text decoration"
    const val TextIndent = "text indent"
    const val VisualTransformation = "visual transformation"
    const val ZIndex = "z index"
}

object ViewModelNavRoutes {
    const val Flow = "flow"
    const val LiveData = "live data"
    const val State = "state"
}

object CustomExamplesNavRoutes {
    const val AnimatedDeleteList = "animated delete list"
    const val AnimatedShowList = "animated show list"
    const val AnimatedText = "animated text"
    const val CameraX = "cameraX"
    const val FirstBaselineToTop = "first baseline to top"
    const val StaggeredGridList = "staggered grid list"
}

object ExternalLibrariesNavRoutes {
    const val CoilAccompanist = "coil accompanist"
    const val CoilLandscapist = "coil landscapist"
    const val FlowLayout = "flow layout"
    const val FrescoLandscapist = "fresco landscapist"
    const val GlideAccompanist = "glide accompanist"
    const val GlideLandscapist = "glide landscapist"
    const val Insets = "insets"
    const val Lottie = "lottie"
    const val OrchestraBalloon = "orchestra balloon"
    const val OrchestraColorPicker = "orchestra color picker"
    const val OrchestraSpinner = "orchestra spinner"
    const val Pager = "pager"
    const val RatingBar = "rating bar"
    const val RevealSwipe = "reveal swipe"
    const val SpeedDialFloatingActionButton = "speed dial floating action button"
    const val SwipeRefresh = "swipeRefresh"
    const val SystemUiController = "system ui controller"
}
