package com.steleot.jetpackcompose.playground.utils

import com.steleot.jetpackcompose.playground.navigation.graph.*

val ribbonRoutes = setOf(
    /* 5.2.0 */
    MainNavRoutes.Foundation,
    FoundationNavRoutes.Draggable2d,
    /* 5.1.0 */
    /* 5.0.0 */
    MainNavRoutes.ConstraintLayout,
    ConstraintLayoutNavRoutes.ConstraintGridDsl,
    ConstraintLayoutNavRoutes.ConstraintHorizontalFlow,
    ConstraintLayoutNavRoutes.ConstraintVerticalFlow,
    MainNavRoutes.CustomExamples,
    CustomExamplesNavRoutes.CircleModifier,
    CustomExamplesNavRoutes.LogSizeModifier,
    MainNavRoutes.Foundation,
    FoundationNavRoutes.AnchoredDraggable,
    FoundationNavRoutes.BasicMarquee,
    FoundationNavRoutes.BasicTextField2,
    FoundationNavRoutes.BasicTextField,
    FoundationNavRoutes.FlowColumn,
    FoundationNavRoutes.FlowRow,
    FoundationNavRoutes.HorizontalPager,
    FoundationNavRoutes.Hoverable,
    FoundationNavRoutes.LazyHorizontalStaggeredGrid,
    FoundationNavRoutes.LazyVerticalStaggeredGrid,
    FoundationNavRoutes.Hoverable,
    FoundationNavRoutes.Magnifier,
    FoundationNavRoutes.SnapFlingBehavior,
    FoundationNavRoutes.VerticalPager,
    MainNavRoutes.Material3,
    Material3NavRoutes.DatePicker,
    Material3NavRoutes.HorizontalDivider,
    Material3NavRoutes.MultiChoiceSegmentedButtonRow,
    Material3NavRoutes.PlainTooltip,
    Material3NavRoutes.RichTooltip,
    Material3NavRoutes.SingleChoiceSegmentedButtonRow,
    Material3NavRoutes.SearchBar,
    Material3NavRoutes.SnackBar3,
    Material3NavRoutes.TimePicker,
    Material3NavRoutes.VerticalDivider,
    Material3NavRoutes.WindowWidthSizeClass,
    MainNavRoutes.Material,
    MaterialNavRoutes.PullRefresh,
    MainNavRoutes.Ui,
    UiNavRoutes.LookaheadScope,
    UiNavRoutes.PointerHoverIcon,
    UiNavRoutes.Semantics,
    UiNavRoutes.TextMotion,
)
