package com.steleot.jetpackcompose.playground.navigation

object MainNavRoutes {
    const val Main = "main"
    const val Search = "search"
    const val Activity = "activity"
    const val Animation = "animation"
    const val ConstraintLayout = "constraint layout"
    const val CustomExamples = "custom examples"
    const val ExternalLibraries = "external libraries"
    const val Foundation = "foundation"
    const val FoundationLayout = "foundation layout"
    const val Material = "material"
    const val MaterialIcons = "material icons"
    const val MaterialIConsExtended = "material icons extended"
    const val Navigation = "navigation"
    const val Paging = "paging"
    const val Runtime = "runtime"
    const val Ui = "ui"
    const val ViewModel = "view model"
    const val Settings = "settings"
    const val Popular = "popular"
    const val Favorites = "favorites"
    const val Articles = "articles"
}

object ActivityNavRoutes {
    const val BackHandler = "back handler"
    const val LauncherForActivityResult1 = "launch for activity result 1"
    const val LauncherForActivityResult2 = "launch for activity result 2"
}

object AnimationNavRoutes {
    const val Animatable = "animatable"
    const val AnimatedContent = "animated content"
    const val AnimatedValues = "animated values"
    const val AnimatedVector = "animated vector"
    const val AnimatedVisibility = "animated visibility"
    const val AnimateEnterExit = "animated enter exit"
    const val AnimationModifier = "animation modifier"
    const val CrossfadeAnimation = "crossfade animation"
    const val DoubleTapToLike = "double tap to like"
    const val ElevationAnimation = "elevation animation"
    const val GestureAnimation = "gesture animation"
    const val InfiniteTransition = "infinite transition"
    const val RotateAnimation = "rotate animation"
    const val ScaleAnimation = "scale animation"
    const val SingleValueColorAnimation = "single value color animation"
    const val SingleValueFloatAnimation = "single value float animation"
    const val SuspendAnimation = "suspend animation"
}

object ConstraintLayoutNavRoutes {
    const val Barrier = "barrier"
    const val Chain = "chain"
    const val Circular = "circular"
    const val ConstraintSet = "constraint set"
    const val CreateGuideline = "create guideline"
    const val CreateRefs = "create refs"
    const val JsonConstraintSet = "json constraint set"
    const val JsonConstraintSetWithVariables = "json constraint set with variables"
    const val MotionLayout1 = "motion layout 1"
    const val MotionLayout2 = "motion layout 2"
    const val MotionLayout3 = "motion layout 3"
}

object FoundationNavRoutes {
    const val Background = "background"
    const val Border = "border"
    const val Canvas = "canvas"
    const val Clickable = "clickable"
    const val ClickableText = "clickable text"
    const val CombinedClickable = "combined clickable"
    const val DragGestureDetector = "drag gesture detector"
    const val Draggable = "draggable"
    const val Focusable = "focusable"
    const val Image = "image"
    const val InteractionSource = "interaction source"
    const val LazyColumn = "lazy column"
    const val LazyGrid = "lazy grid"
    const val LazyRow = "lazy row"
    const val LocalOverScrollConfiguration = "local overScroll configuration"
    const val ProgressSemantics = "progress semantics"
    const val Scrollable = "scrollable"
    const val Scroller = "scroller"
    const val SelectableGroup = "selectable group"
    const val Selectable = "selectable"
    const val SelectionContainer = "selection container"
    const val Shape = "shape"
    const val StickyHeader = "sticky header"
    const val Toggeable = "toggeable"
    const val TransformGesture = "transform gesture"
    const val Transformable = "transformable"
}

object FoundationLayoutNavRoutes {
    const val AbsolutePadding = "absolute padding"
    const val AspectRatio = "aspect ratio"
    const val Box = "box"
    const val BoxWithConstraints = "box with constraints"
    const val Column = "column"
    const val DefaultMinSize = "default min size"
    const val Intrinsic = "intrinsic"
    const val MatchParentSize = "match parent size"
    const val Offset = "offset"
    const val PaddingFromBaseline = "padding from baseline"
    const val PaddingFrom = "padding from"
    const val Padding = "padding"
    const val Row = "row"
    const val Size = "size"
    const val Spacer = "spacer"
    const val Weight = "weight"
}

object MaterialNavRoutes {
    const val AlertDialog = "alert dialog"
    const val BackdropScaffold = "backdrop scaffold"
    const val BadgedBox = "badged box"
    const val BottomAppBar = "bottom app bar"
    const val BottomDrawer = "bottom drawer layout"
    const val BottomNavigation = "bottom navigation"
    const val BottomSheetScaffold = "bottom sheet scaffold"
    const val Button = "button"
    const val Card = "card"
    const val Checkbox = "checkbox"
    const val Divider = "divider"
    const val DropdownMenu = "dropdown menu"
    const val FloatingActionButton = "floating action button"
    const val ExtendedFloatingActionButton = "extended floating action button"
    const val Elevation = "elevation"
    const val IconButton = "icon button"
    const val IconToggleButton = "icon toggle button"
    const val Icon = "icon"
    const val ListItem = "list item"
    const val LocalAbsoluteElevation = "local absolute elevation"
    const val LocalContentAlpha = "local content alpha"
    const val LocalContentColor = "local content color"
    const val MaterialTheme = "material theme"
    const val ModalBottomSheetLayout = "modal bottom sheet layout"
    const val ModalDrawer = "modal drawer"
    const val NavigationRail = "navigation rail"
    const val OutlinedTextField = "outlined text field"
    const val Progress = "progress"
    const val RadioButton = "radio button"
    const val RangeSlider = "range slider"
    const val Scaffold = "scaffold"
    const val ScrollableTabRow = "scrollable Tab row"
    const val Slider = "slider"
    const val SnackBar = "snackBar"
    const val Surface = "surface"
    const val Swipeable = "swipeable"
    const val SwipeToDismiss = "swipe to dismiss"
    const val Switch = "switch"
    const val TabRow = "tab row"
    const val TextField = "text field"
    const val Text = "text"
    const val TopAppBar = "top app bar"
    const val TriStateCheckbox = "tri state checkbox"
}

object MaterialIconsNavRoutes {
    const val Filled = "filled"
    const val Outlined = "outlined"
    const val Rounded = "rounded"
    const val Sharp = "sharp"
    const val TwoTone = "twotone"
}

object MaterialIconsExtendedNavRoutes {
    const val ExtendedFilled = "extended filled"
    const val ExtendedOutlined = "extended outlined"
    const val ExtendedRounded = "extended rounded"
    const val ExtendedSharp = "extended sharp"
    const val ExtendedTwoTone = "extended twotone"
}

object RuntimeNavRoutes {
    const val CollectAsState = "collect as state"
    const val CompositionLocal = "composition local"
    const val DerivedState = "derived state"
    const val DisposableEffect = "disposable effect"
    const val Immutable = "immutable"
    const val Key = "key"
    const val LaunchedEffect = "launched effect"
    const val MutableStateList = "mutableState list"
    const val MutableStateMap = "mutableState map"
    const val ProduceState = "produce state"
    const val RememberCoroutineScope = "remember coroutine scope"
    const val RememberSaveable = "remember saveable"
    const val RememberSaveableStateHolder = "remember saveable state holder"
    const val Remember = "remember"
    const val Saver = "saver"
    const val SideEffect = "side effect"
    const val SnapshotFlow = "snapshot flow"
}

object UiNavRoutes {
    const val AlignmentLine = "alignment line"
    const val Alpha = "alpha"
    const val AndroidViewBinding = "android view binding"
    const val AnnotatedString = "annotated string"
    const val Blur = "blur"
    const val Brush = "brush"
    const val Clip = "clip"
    const val ClipToBounds = "clip to bounds"
    const val Color = "color"
    const val DebugInspectorInfo = "debug inspector info"
    const val Dialog = "dialog"
    const val Drawable = "drawable"
    const val DrawBehind = "draw behind"
    const val DrawWithCache = "draw with cache"
    const val DrawWithContent = "draw with content"
    const val Font = "font"
    const val GraphicsLayer = "graphics layer"
    const val ImageBitmapToPixelMap = "image bitmap to pixel map"
    const val Inspectable = "inspectable"
    const val LayoutId = "layout id"
    const val Layout = "layout"
    const val LocalAccessibilityManager = "local accessibility manager"
    const val LocalAutofill = "local autofill"
    const val LocalAutofillTree = "local autofill tree"
    const val LocalClipboardManager = "local clipboard manager"
    const val LocalConfiguration = "local configuration"
    const val LocalContext = "local context"
    const val LocalDensity = "local density"
    const val LocalFocusManager = "local focus manager"
    const val LocalFontLoader = "local font loader"
    const val LocalHapticFeedback = "local haptic feedback"
    const val LocalLayoutDirection = "local layout direction"
    const val LocalLifecycleOwner = "local lifecycle owner"
    const val LocalSavedStateRegistryOwner = "local saved state registry owner"
    const val LocalSoftwareKeyboardController = "local software keyboard controller"
    const val LocalTextInputService = "local text input service"
    const val LocalTextToolbar = "local text toolbar"
    const val LocalUriHandler = "local uri handler"
    const val LocalViewConfiguration = "local view configuration"
    const val LocalWindowInfo = "local window info"
    const val NestedScroll = "nested scroll"
    const val OnGloballyPositioned = "on globally positioned"
    const val OnKeyEvent = "on key event"
    const val OnSizeChanged = "on size changed"
    const val Paint = "paint"
    const val PathEffect = "path effect"
    const val PointerInput = "pointer input"
    const val Popup = "popup"
    const val Primitive = "primitive"
    const val RelocationRequester = "relocation requester"
    const val Rotate = "rotate"
    const val Scale = "scale"
    const val Shadow = "shadow"
    const val SpanStyle = "span style"
    const val String = "string"
    const val SubComposeLayout = "sub compose layout"
    const val TestTag = "test tag"
    const val TextDecoration = "text decoration"
    const val TextIndent = "text indent"
    const val VisualTransformation = "visual transformation"
    const val ZIndex = "z index"
}

object ViewModelNavRoutes {
    const val Flow = "flow"
    const val LiveData = "live data"
    const val State = "state"
}

object CustomExamplesNavRoutes {
    const val AdMobBanner = "ad mob banner"
    const val AnimatedDeleteList = "animated delete list"
    const val AnimatedExtendedFloatingActionButton = "animated extended floating action button"
    const val AnimatedShowList = "animated show list"
    const val AnimatedText = "animated text"
    const val BarChart = "bar chart"
    const val CameraX = "cameraX"
    const val CollapsingToolbar = "collapsing toolbar"
    const val ColorMatrix = "color matrix"
    const val CurvedScrollView = "curved scroll view"
    const val CurvedText = "curved text"
    const val FirstBaselineToTop = "first baseline to top"
    const val MessageBubble = "message bubble"
    const val StaggeredGridList = "staggered grid list"
    const val StyledText = "styled text"
    const val TearDrop = "tear drop"
}

object ExternalLibrariesNavRoutes {
    const val CoilLandscapist = "coil landscapist"
    const val Coil = "coil"
    const val ComposeBarcodes = "compose barcodes"
    const val ComposeCharts = "compose charts"
    const val ComposeMarkdown = "compose markdown"
    const val ComposeNeumorphism = "compose neumorphism"
    const val ComposeRichTextPrinting = "compose rich text printing"
    const val ComposeRichTextSlideshow = "compose rich text slideshow"
    const val ComposeRichTextUiMaterial = "compose rich text ui material"
    const val ComposeRichTextUi = "compose rich text ui"
    const val ComposeZoomableImage = "compose zoomable image"
    const val DrawablePainterAccompanist = "drawable painter accompanist"
    const val FlowLayoutAccompanist = "flow layout accompanist"
    const val FontAwesome = "font awesome"
    const val FrescoLandscapist = "fresco landscapist"
    const val GlideLandscapist = "glide landscapist"
    const val InsetsAccompanist = "insets accompanist"
    const val Lottie = "lottie"
    const val NavigationAnimationAccompanist = "navigation animation accompanist"
    const val NavigationMaterialAccompanist = "navigation material accompanist"
    const val OrchestraBalloon = "orchestra balloon"
    const val OrchestraColorPicker = "orchestra color picker"
    const val OrchestraSpinner = "orchestra spinner"
    const val PagerAccompanist = "pager accompanist"
    const val PaletteLandscapist = "palette landscapist"
    const val PermissionsAccompanist = "permissions accompanist"
    const val PlaceholderAccompanist = "placeholder accompanist"
    const val RatingBar = "rating bar"
    const val RevealSwipe = "reveal swipe"
    const val SpeedDialFloatingActionButton = "speed dial floating action button"
    const val StageStepBar = "stage step bar"
    const val SwipeRefreshAccompanist = "swipe refresh accompanist"
    const val SystemUiControllerAccompanist = "system ui controller accompanist"
}
