object Versions {

    /* build tools */
    const val buildTools = "31.0.0"

    /* kotlin */
    const val kotlin = "1.5.21"

    /* plugins */
    const val androidPlugin = "7.0.0"
    const val googleServices = "4.3.8"
    const val crashlytics = "2.7.1"
    const val benManes = "0.39.0"
    const val detekt = "1.18.0-RC3"
    const val doctor = "0.7.1"
    const val protobufPlugin = "0.8.17"

    /* libraries */
    const val compose = "1.1.0-alpha01"
    const val composeConstraint = "1.0.0-beta02"
    const val composePaging = "1.0.0-alpha12"
    const val composeWear = "1.0.0-alpha03"
    const val navigation = "2.4.0-alpha06"
    const val core = "1.7.0-alpha01"
    const val activity = "1.3.1"
    const val appCompat = "1.4.0-alpha03"
    const val lifecycle = "2.4.0-alpha03"
    const val firebase = "28.3.1"
    const val hilt = "2.38.1"
    const val hiltCompose = "1.0.0-alpha03"
    const val startUp = "1.1.0"
    const val coroutines = "1.5.0"
    const val dataStore = "1.0.0"
    const val protobuf = "4.0.0-rc-2"
    const val playCore = "1.10.0"
    const val playCoreKtx = "1.8.1"
    const val cameraX = "1.1.0-alpha07"
    const val cameraView = "1.0.0-alpha27"
    const val accompanist = "0.16.0"
    const val landscapist = "1.3.1"
    const val orchestra = "1.1.0"
    const val coil = "1.3.2"
    const val glide = "4.12.0"
    const val fresco = "2.5.0"
    const val timber = "4.7.1"
    const val lottie = "4.0.0"
    const val ratingBar = "1.1.0"
    const val revealSwipe = "1.0.0-beta05"
    const val speedDial = "1.0.0-beta03"
    const val fontAwesome = "1.0.0-beta02"
    const val composeCharts = "0.3.1"
    const val composeNeumorphism = "1.0.0-alpha"
    const val composeMarkdown = "0.2.5"
    const val composeBarcodes = "1.0.0"
    const val composeRichtext = "0.6.0"
    const val adMob = "20.2.0"
}