object Versions {

    /* build tools */
    const val buildTools = "31.0.0"

    /* kotlin */
    const val kotlin = "1.5.31"

    /* plugins */
    const val androidPlugin = "7.0.2"
    const val googleServices = "4.3.10"
    const val crashlytics = "2.7.1"
    const val benManes = "0.39.0"
    const val detekt = "1.18.1"
    const val doctor = "0.7.3"
    const val protobufPlugin = "0.8.17"
    const val playPublisher = "3.6.0"

    /* libraries */
    const val compose = "1.1.0-alpha05"
    const val composeConstraint = "1.0.0-rc01"
    const val composePaging = "1.0.0-alpha13"
    const val composeWear = "1.0.0-alpha07"
    const val navigation = "2.4.0-alpha10"
    const val core = "1.7.0-alpha02"
    const val activity = "1.4.0-beta01"
    const val appCompat = "1.4.0-beta01"
    const val lifecycle = "2.4.0-alpha03"
    const val firebase = "28.4.1"
    const val hilt = "2.39.1"
    const val hiltCompose = "1.0.0-alpha03"
    const val startUp = "1.1.0"
    const val coroutines = "1.5.2"
    const val dataStore = "1.0.0"
    const val protobuf = "4.0.0-rc-2"
    const val playCore = "1.10.2"
    const val playCoreKtx = "1.8.1"
    const val cameraX = "1.1.0-alpha09"
    const val cameraView = "1.0.0-alpha29"
    const val workManager = "2.7.0-rc01"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val kotlinxSerializationConverter = "0.8.0"
    const val kotlinxSerialization = "1.3.0"
    const val accompanist = "0.19.0"
    const val landscapist = "1.3.7"
    const val orchestra = "1.1.0"
    const val coil = "1.3.2"
    const val glide = "4.12.0"
    const val fresco = "2.5.0"
    const val timber = "5.0.1"
    const val lottie = "4.1.0"
    const val ratingBar = "1.1.1"
    const val revealSwipe = "1.0.0"
    const val speedDial = "1.0.0-beta03"
    const val fontAwesome = "1.0.0-beta02"
    const val composeCharts = "0.3.2"
    const val composeNeumorphism = "1.0.0-alpha02"
    const val composeMarkdown = "0.2.6"
    const val composeBarcodes = "1.0.2"
    const val composeRichtext = "0.8.1"
    const val zoomableImage = "0.1.0"
    const val stageStepBar = "0.0.1"
    const val plot = "0.1.2"
    const val composeTimelineView = "1.0.2"
    const val adMob = "20.4.0"
    const val playServicesAuth = "19.2.0"
    const val test = "1.4.1-alpha02"
}