package com.steleot.jetpackcompose.playground.navigation.graph

object Material3NavRoutes {
    const val AlertDialog3 = "alert dialog 3"
    const val BadgedBox3 = "badged box 3"
    const val Badge3 = "badge 3"
    const val Button3 = "button 3"
    const val Card3 = "card 3"
    const val CenterAlignedTopAppBar = "center aligned top app bar"
    const val Checkbox3 = "checkbox 3"
    const val Divider3 = "divider 3"
    const val DropdownMenu3 = "dropdown menu 3"
    const val ElevatedButton = "elevated button"
    const val ElevatedCard = "elevated card"
    const val ExtendedFloatingActionButton3 = "extended floating action button 3"
    const val FilledTonalButton = "filled tonal button"
    const val FloatingActionButton3 = "floating action button 3"
    const val IconButton3 = "icon button 3"
    const val Icon3 = "icon 3"
    const val IconToggleButton3 = "icon toggle button 3"
    const val LargeFloatingActionButton = "large floating action button"
    const val LargeTopAppBar = "large top app bar"
    const val LocalAbsoluteTonalElevation = "local absolute tonal elevation"
    const val LocalContentColor3 = "local content color 3"
    const val LocalMinimumTouchTargetEnforcement = "local minimum touch target enforcement"
    const val LocalTextStyle3 = "local text style 3"
    const val MaterialTheme3 = "material theme 3"
    const val MediumTopAppBar = "medium top app bar"
    const val ModalNavigationDrawer = "modal navigation drawer"
    const val NavigationBar = "navigation bar"
    const val NavigationRail3 = "navigation rail 3"
    const val OutlinedButton3 = "outlined button 3"
    const val OutlinedCard = "outlined card"
    const val ProgressIndicator3 = "progress indicator3"
    const val RadioButton3 = "radio button 3"
    const val Scaffold3 = "scaffold 3"
    const val SmallFloatingActionButton = "small floating action button"
    const val SmallTopAppBar = "small top app bar"
    const val Surface3 = "surface 3"
    const val TextButton3 = "text button 3"
    const val Text3 = "text 3"
}